language: node_js
node_js:
  - "8.9.4"
install: true
cache: yarn
notifications:
  email: false
script:
  - yarn install
  - yarn build
  - yarn add firebase-tools -g
  - firebase deploy --token "$FIREBASE_TOKEN"
